/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type GameLevel = "easy" | "extreme" | "hard" | "medium";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthorizedUser {
  authorizedBy: string;
  chatId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  userId: string;
}

export interface ChatGameTopic {
  chatId: string;
  createdAt: Generated<Timestamp>;
  topicId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Leaderboard {
  chatId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  level: GameLevel;
  score: number;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface User {
  coins: Generated<number>;
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface WordHint {
  createdAt: Generated<Timestamp>;
  hints: string[];
  id: Generated<number>;
  level: GameLevel;
  relatedWords: string[];
  sentence: string;
  updatedAt: Generated<Timestamp>;
  word: string;
}

export interface DB {
  authorizedUsers: AuthorizedUser;
  chatGameTopics: ChatGameTopic;
  leaderboard: Leaderboard;
  users: User;
  wordHints: WordHint;
}
